AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CloudFormation template
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.medium
    Description: Enter instance type (default is t2.micro)


Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c55b159cbfafe1f0
    us-west-1:
      AMI: ami-0a10b27219a5094d7
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
Outputs:
  InstanceID:
    Description: Instance ID of the EC2 instance
    Value: !Ref MyEC2Instance